### ISSUE TITLE
Deploying the app - is it necessary for the Hacakthon demo? 

### ISSUE THREAD

**Issue by bamohan** [bamohan/friends_of_children_with_special_needs#27]
If so, can we look into 
- deploying either to heroku or AWS?
- look into running seed data on the deployed app

**Comment by dkackar** [comment]
Yes will be a good idea to deploy . I will start on the initial issue I signed up for today and will seed some models at least

**Comment by bamohan** [comment]
@dkackar - all models are now checked in

**Comment by ollyajoke** [comment]
So the answer is: "Demo's is fine. We don't need a complete ready to ship product."
Looks like we don't have to deploy it unless we want to. 
The alternatives are:
- The app can be deployed to Heroku, however, it can be active only 18 hours out of 24 hours per day on a free basis. 
- The app can be deployed to AWS, it will be active 24/7 for 1 year for free. However, they still ask for billing info for future.
- We can stick with local demo and deploy the app later when necessary.

**Comment by bamohan** [comment]
I am ok with not deploying for the hackathon. We can deploy to AWS for a year once we are done in the next few weeks. I will close the issue for now. @dkackar @jackiesyu - please reopen the issue if you disagree.
